/**
 * DigiFusion Agent Harness — Phase 4, Piece 2: Harness Charter
 * ==============================================================
 *
 * Generated governance document for an agent estate. Living artifact,
 * not a one-time PDF. The charter IS the product.
 *
 * Sections: Named Governor, Error Budget, Verification Policy,
 *           Perimeter Map, Trace Retention, Restricted Agents
 */

import { getSupabase } from '../../supabaseClient.js';
import { getPerimeterMap } from '../perimeter.js';
import { MAX_UNVERIFIED_STEPS } from '../verify.js';
import { scoreHarnessHealth } from './harnessHealth.js';

export async function generateCharter({
  clientId, governor, tokenCeiling = 200_000,
  costCeilingUsdMills = 10_000, monthlyCostCeilingUsdMills = 50_000,
  retentionDays = 90, restrictedAgents = [],
}) {
  const health = await scoreHarnessHealth();
  const perimeter = await getPerimeterMap();
  const lines = [];

  lines.push(`# Agent Estate Governance Charter`);
  lines.push(`**Client:** ${clientId}`);
  lines.push(`**Generated:** ${new Date().toISOString().split('T')[0]}`);
  lines.push(`**Harness Health Score:** ${health.total}/100 — ${health.band.label}`);
  lines.push('');
  lines.push('This charter is a living document. It regenerates when the estate changes.');
  lines.push('');

  // §1 — Named Governor
  lines.push('## 1. Named Governor');
  lines.push('');
  lines.push(`The named governor is **${governor || '«name the governor»'}**.`);
  lines.push('');
  lines.push('The governor holds kill-switch authority: they may suspend any agent, revoke any API key, or halt any run. No agent runs unattended without a named governor who has verified the stop works within 30 days.');
  lines.push('');

  // §2 — Error Budget
  lines.push('## 2. Error Budget');
  lines.push('');
  lines.push(`| Ceiling | Limit |`);
  lines.push(`|---|---|`);
  lines.push(`| Tokens per run | ${tokenCeiling.toLocaleString()} |`);
  lines.push(`| Cost per run | $${(costCeilingUsdMills / 1000).toFixed(2)} |`);
  lines.push(`| Monthly cost | $${(monthlyCostCeilingUsdMills / 1000).toFixed(2)} |`);
  lines.push('');
  lines.push('A run that exceeds any ceiling is **aborted, not degraded.** The governor is notified within the hour.');
  lines.push('');

  // §3 — Verification Policy
  lines.push('## 3. Verification Policy');
  lines.push('');
  lines.push(`**Maximum unverified steps:** ${MAX_UNVERIFIED_STEPS}. Chains exceeding this are rejected at the orchestration layer. Verification resets the chain.`);
  lines.push('Required check types: **schema**, **non_empty**, **citation** (any factual claim must carry a source).');
  lines.push('');
  // §4 — Perimeter Map
  lines.push('## 4. Perimeter Map');
  lines.push('');
  lines.push('Which agent may read which knowledge namespace. The point is decorrelation — agents that read different things fail differently.');
  lines.push('');
  lines.push('| Agent | Allowed Namespaces |');
  lines.push('|---|---|');
  for (const [agentId, namespaces] of Object.entries(perimeter)) {
    const ns = [...namespaces].slice(0, 3).join(', ');
    const more = namespaces.size > 3 ? ` +${namespaces.size - 3}` : '';
    lines.push(`| ${agentId} | ${ns}${more} |`);
  }
  lines.push('');
  lines.push('**Success test:** a deliberately poisoned knowledge-base entry should damage exactly one agent, not all.');
  lines.push('');

  // §5 — Trace Retention
  lines.push('## 5. Trace Retention');
  lines.push('');
  lines.push(`**Retention:** ${retentionDays} days. Every invocation writes one row: run id, agent, step index, input hash, output hash, tokens, cost, duration, verdict. Traces are SHA-256 hashed and cannot be altered without detection.`);
  lines.push('');

  // §6 — Restricted Agents
  if (restrictedAgents.length > 0) {
    lines.push('## 6. Restricted Agents');
    lines.push('');
    lines.push('These agents must NOT hold write access to the outbound sender and the register in the same context — that combination is how prompt injection becomes a message to every contact.');
    for (const a of restrictedAgents) lines.push(`- **${a}**`);
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(`**Last verified:** ${new Date().toISOString()}`);
  lines.push(`**Health at verification:** ${health.total}/100 — ${health.band.label}`);
  if (health.blocked.length) lines.push(`**⚠ Blocked:** ${health.blocked.join(', ')} — fix before next review.`);
  lines.push('');
  lines.push('*Generated by the DigiFusion Agent Harness. Not a policy written once and filed — it regenerates from the live estate. Renewal keeps it current.*');

  return lines.join('\n');
}

// ── Persistence ──────────────────────────────────────────────────────────────

export async function saveCharter({ clientId, governor, ...opts }) {
  const db = getSupabase();
  if (!db) throw new Error('[Charter] No DB');
  const charter = await generateCharter({ clientId, governor, ...opts });
  const health = await scoreHarnessHealth();
  const { error } = await db.from('client_charters').upsert({
    client_id: clientId, charter, governor,
    health_score: health.total, health_band: health.band.id,
    token_ceiling: opts.tokenCeiling || 200_000,
    cost_ceiling_mills: opts.costCeilingUsdMills || 10_000,
    monthly_cost_ceiling_mills: opts.monthlyCostCeilingUsdMills || 50_000,
    retention_days: opts.retentionDays || 90,
    generated_at: new Date().toISOString(),
  }, { onConflict: 'client_id' });
  if (error) { console.warn('[Charter] Save failed:', error.message); throw error; }
  console.log(`[Charter] Generated for ${clientId} — health ${health.total}/100`);
  return { charter, health };
}

export async function getCharter(clientId) {
  const db = getSupabase();
  if (!db) return null;
  const { data } = await db.from('client_charters').select('*').eq('client_id', clientId).maybeSingle();
  return data || null;
}

export async function listCharters() {
  const db = getSupabase();
  if (!db) return [];
  const { data } = await db.from('client_charters').select('client_id, governor, health_score, health_band, generated_at').order('generated_at', { ascending: false });
  return data || [];
}

